title: HP-Connect Sweden
description: En ideell förening och har till ändamål att verka för främjande av erfarenhetsutbytet mellan användare av företagsprodukter.
theme: jekyll-theme-cayman
menu1: index
menu2: meetings
menu3: member-info
menu4: the-board
menu5: contact-us